language: objective-c
os:
  - osx
before_install:
  - brew install ruby
  - brew install caskroom/cask/brew-cask
  - brew update
  - brew cask update
  - gem install bundler
  - bundle install --path vendor/bundle
  - bundle exec rake brew:bundle
script:
  - bundle exec rake spec
