brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
  install_packages:
    - brew-cask
    - ag
    - carthage
    - fish
    - ghq
    - git
    - git-now
    - go
    - hub
    - lua
    - nodebrew
    - peco
    - rbenv
    - readline
    - reattach-to-user-namespace
    - ruby-build
    - sbt
    - scala
    - tig
    - tmux
    - vim --with-lua
    - z
  install_apps:
    - appcleaner
    - alfred
    - bartender
    - atom
    - bettertouchtool
    - dropbox
    - iterm2
    - karabiner
    - seil
    - spark
    - sourcetree
    - virtualbox
    - vagrant
